"use client";

import { useState } from "react";
import { useAuth } from "@/lib/firebase/auth-context";
import { Button } from "@/components/ui/button";
import { Copy, Check, X, FileText, Mail, MessageSquare, Instagram, Sparkles, Download, Loader2 } from "lucide-react";
import { GenerationType, GENERATION_TYPE_LABELS } from "@/lib/ai/types";

interface GenerationOutputProps {
  content: string;
  type: GenerationType;
  targetCompany?: string;
  targetRole?: string;
  onDismiss: () => void;
}

export default function GenerationOutput({ content, type, targetCompany, targetRole, onDismiss }: GenerationOutputProps) {
  const { user } = useAuth();
  const [copied, setCopied] = useState(false);
  const [exportingDocx, setExportingDocx] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  const typeIcon = () => {
    switch (type) {
      case "cover_letter": return <FileText className="w-5 h-5" />;
      case "cold_email": return <Mail className="w-5 h-5" />;
      case "cold_dm_instagram": return <Instagram className="w-5 h-5" />;
      case "cold_wa": return <MessageSquare className="w-5 h-5" />;
      case "cold_linkedin": return <Mail className="w-5 h-5" />;
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = content;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExport = async (format: "docx" | "pdf") => {
    const setter = format === "docx" ? setExportingDocx : setExportingPdf;
    setter(true);
    try {
      const token = await user?.getIdToken();
      if (!token) return;

      const res = await fetch("/api/ai/export", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          content,
          type,
          format,
          targetCompany: targetCompany || undefined,
          targetRole: targetRole || undefined,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Export failed");
      }

      const blob = await res.blob();
      const contentDisposition = res.headers.get("Content-Disposition") || "";
      const filenameMatch = contentDisposition.match(/filename="(.+)"/);
      const filename = filenameMatch ? filenameMatch[1] : `export.${format}`;

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Export failed:", err);
      alert("Export failed. Please try again.");
    } finally {
      setter(false);
    }
  };

  return (
    <div className="animate-in fade-in slide-in-from-2 duration-300 rounded-xl border-2 border-primary/30 bg-gradient-to-b from-primary/5 to-transparent overflow-hidden">
      <div className="p-4 sm:p-5 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary">
              {typeIcon()}
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">
                {GENERATION_TYPE_LABELS[type]}
              </p>
              <p className="text-[11px] text-muted-foreground flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                Generated by AI
              </p>
            </div>
          </div>
          <button
            onClick={onDismiss}
            className="p-1.5 rounded-md hover:bg-muted transition-colors"
          >
            <X className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>

        <div className="bg-background border border-border rounded-lg p-4 max-h-80 overflow-y-auto">
          <pre className="whitespace-pre-wrap text-sm text-foreground font-sans leading-relaxed">
            {content}
          </pre>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            className="flex items-center gap-1.5 h-8"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-green-500" />
                <span className="text-xs">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span className="text-xs">Copy</span>
              </>
            )}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleExport("docx")}
            disabled={exportingDocx}
            className="flex items-center gap-1.5 h-8"
          >
            {exportingDocx ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Download className="w-3.5 h-3.5" />
            )}
            <span className="text-xs">.docx</span>
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleExport("pdf")}
            disabled={exportingPdf}
            className="flex items-center gap-1.5 h-8"
          >
            {exportingPdf ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Download className="w-3.5 h-3.5" />
            )}
            <span className="text-xs">.pdf</span>
          </Button>
        </div>
      </div>
    </div>
  );
}