name: VPS Staging Deployment

on:
  push:
    branches:
<<<<<<< HEAD
      - dev 
=======
      - dev
>>>>>>> ec4e944170bd7f2863617fbcd2c8b0d89b424d71

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  deploy:
    needs: check-quality
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/jobtracker-staging
            git pull origin dev
            npm install
<<<<<<< HEAD
<<<<<<<< HEAD:.github/workflows/deploy-staging.yml
            npm run build
            pm2 restart jobtracker-staging
========
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            pm2 restart jobtracker-prod
            sudo rm -rf /var/cache/nginx/*
            sleep 10
>>>>>>>> ec4e944170bd7f2863617fbcd2c8b0d89b424d71:.github/workflows/deploy-prod.yml
=======
            pm2 restart jobtracker-staging
            sudo rm -rf /var/cache/nginx/*
>>>>>>> ec4e944170bd7f2863617fbcd2c8b0d89b424d71
